### ISSUE TITLE
Endpoint to list notes by tag

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#11]
For note discovery (while still preserving some privacy), we need an endpoint which would allow users to retrieve notes by their tag where `tag` could include some degree of "fuzziness". Here is a proposal for how the endpoint could look like:

#### Request
- `block_num` - only blocks after this number will be queried.
- `tag_bits` - number of leading bits of the tag to consider for matching. This could be an enum with a fairly small set of values - e.g., 8, 16, 24, 32, 64.
- `tag_value` - value of the tag masked by the number of bits specified above. For example, if `tag_bits` is `8`, then `tag_value` could be an 8-bit value.

Another potential approach for "fuzzy matching" is to use bloom filters instead of `tag_bits`/`tag_value` combination as discussed in https://github.com/0xPolygonMiden/miden-base/discussions/126#discussioncomment-5994317.

#### Response
- `chain_tip` - number of the latest block in the chain.
- `block_num` - number of the block in which the first note matching the criteria was found.
- `notes` - a list of notes found in the block where each note is a tuple `(note_hash, sender, tag, num_assets, note_index, merkle_path)`.
  - `merkle_path` in the above would be compressed Merkle path such that instead of sending roots of empty subtrees, we'd send a simple bitmask indicating which nodes in the path are roots of empty subtrees.

The response would return data for only one block. The user of the endpoint could then check if `chain_tip == block_num`, and if not, make another request using `block_num + 1`.

To support this endpoint on the store side we need:
- Add `notes` table to the database. This table would have the following fields:
  - `block_num` (u32) - identifier for the block in which the note was created.
  - `note_index` (u32) - index of the note in the block's note tree. A tuple `(block_num, note_index)` would be the primary key for this table.
  - `note_hash` (blob)
  - `sender` (u64)
  - `tag` (u64)
  - `num_assets` (u8)
  - `merkle_path` (blob) - the compressed Merkle path
- Build either in-memory or db-native index for looking up notes by tag. The specifics of this would depend on whether we code with bit ranges or a bloom filter approach.

**Comment by bobbinth** [comment]
If we can make this work with bloom filters, we could combine this endpoint with an endpoint to retrieve notes by sender. Basically, we'd send a single bloom filter which combines info about all the notes we are interested in, and any note which gives a positive on tag or sender would be returned.

One way to make this works is as follows:

1. For each block we pre-compute a bloom filter containing all note tags and senders. For block $n$ we would have a bloom filter $B_n$.
2. The user would send in a bloom filter $U$ containing all the notes they are interested in (plus some random data).
3. We would compute there intersection of $U$ and $B_n$ starting with $n$ set to the input parameter `block_num`. If the intersection is empty, we move to the next $n$.
4. If the intersection is not empty, then we run all notes for this block through $U$ and return all matching notes.

However, this approach has several practical challenges:

1. Assuming each block may contain thousands of notes, size of $B_n$ would need to be quite big to keep the false-positive rate manageable. My guess is that we'd need somewhere between 10KB and 20KB per block.
2. To compute an intersection of of $B_n$ and $U$, both filters must have the same number of bits (or at least that's my understanding of how bloom filters work). Thus, $U$ would have to be quite large as well (and we'd need to send it with every request).
  a. It also seems to me that computing $U$ might be challenging as - or at least I'm not sure what strategy should be used here to set the desired false-positive rate.
4. I'm not sure how expensive step 4 would be. It can certainly be parallelized, but it won't really help if we need to handle multiple similar requests at the same time.

**Comment by bobbinth** [comment]
> Assuming each block may contain thousands of notes, size of $B_n$ would need to be quite big to keep the false-positive rate manageable. My guess is that we'd need somewhere between 10KB and 20KB per block.

Actually, we could have multiple filters per block. For example, we could define bloom filter size to be 128 bytes (which should be enough to contain 50 values with false-positive rate of 0.1%) and then if a block contains more than 50 notes, we'd have multiple bloom filters for this block.

This would alleviate challenges 1 and 2 - but figuring out the exact parameters and the overall efficiency of this scheme is still not clear to me.

**Comment by bobbinth** [comment]
Looking into bloom filters a bit more (e.g., [here](https://arxiv.org/pdf/2009.11789.pdf) it seems like there might be a fundamental tradeoff between false positive rate we get from intersection of $B_n$ and $U$ and $U$ itself. Meaning, if we make false-positive rate high for $U$ we'll also get a very high false positive rate for intersection of $B_n$ and $U$ and that means we'd need to examine most blocks. And if make false positive rate of $U$ too low, we won't get much privacy. But maybe that's unavoidable regardless of the methodology used.

**Comment by hackaugusto** [comment]
> For each block we pre-compute a bloom filter containing all note tags and senders. For block we would have a bloom filter .

IMO we should not have a bloom filter per block. That means queries scales with number of blocks, which IMO is not what we want.

An alternative is just to allow the user to send a query bloom filter, and compare that against the tags in the DB. Something like `SELECT * FROM notes WHERE notes.tag = notes.tag & :bloom`, and then we can tune the query to make sure indexes are used to perform well.

**Comment by hackaugusto** [comment]
superseeded by #43
