### ISSUE TITLE
Add API specifications to the documentation of miden-node

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#129]
Qualitative documentation is of paramount importance for the understanding and onboarding of new users, correct general operation and maintenance of our software.

We would like to add a section to the README listing the different rpc endpoints supported by the RPC and by the Store api's.

All needed information should be available in the code in the following files: 
- RPC api:
https://github.com/0xPolygonMiden/miden-node/blob/9e3ddb97a7c873d8ea59d8576e6c0e893617ae5b/rpc/src/server/api.rs#L52-L88
- RPC proto: 
https://github.com/0xPolygonMiden/miden-node/blob/9e3ddb97a7c873d8ea59d8576e6c0e893617ae5b/proto/proto/rpc.proto#L8-L13
- Store api:
https://github.com/0xPolygonMiden/miden-node/blob/9e3ddb97a7c873d8ea59d8576e6c0e893617ae5b/store/src/server/api.rs#L30-L177
- Store proto: 
https://github.com/0xPolygonMiden/miden-node/blob/9e3ddb97a7c873d8ea59d8576e6c0e893617ae5b/proto/proto/store.proto#L10-L17

And additional information regarding the architecture should be available in the README: 
https://github.com/0xPolygonMiden/miden-node/tree/main?tab=readme-ov-file#architecture

Looking at the diagram should also be informative to understand the global architecture.
```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/miden-node/pull/136
```

**Comment by bobbinth** [comment]
I would probably create separate readme files for RPC and store components in their respective directories.

In terms of sections, I'd probably follow the similar structure as in the main readme:

1. Short intro (we can probably skip the status sub-section).
2. Architecture - could be just stubbed out for now, and we can fill it in later.
3. Usage - info on how to start the specific component.
4. API - description of the API. This would be the main focus for this issue. We should list the available endpoints and provide a brief description of each.

I would also probably split this into two PRs - one for the RPC and the other one for the store component (to be done after we merge the RPC one).
