### ISSUE TITLE
`SyncState` endpoint: SQL error

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#130]
On some calls to the `SyncState` RPC, we get the error

```
no such table: rarray Caused by: Error code 1: SQL error or missing database
```

It doesn't seem to happen on every call though.

**Comment by igamigo** [comment]
On some other calls I have gotten this error:


```
request: SyncStateRequest { block_num: 0, account_ids: [AccountId { id: 9736325183183255499 }, AccountId { id: 1621726699017415300 }], note_tags: [], nullifiers: [] }

rpc api error: rpc request failed: status: Internal, message: "Mmr does not contain position 343", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "content-length": "0", "date": "Sun, 31 Dec 2023 04:02:22 GMT"} }
```

The number reported in the message also changed and went up monotonically over time in the few tests I did.

**Comment by plafer** [comment]
@igamigo this is fixed in #131

**Comment by bobbinth** [comment]
My understanding is that this error can happen if the `array` extension is not loaded (i.e., as illustrated [here](https://docs.rs/rusqlite/latest/rusqlite/vtab/array/index.html)). We do load it [here](https://github.com/0xPolygonMiden/miden-node/blob/main/store/src/db/mod.rs#L63) but I wonder if there is some kind of weird interaction with the connection pool that is causing this.

**Comment by bobbinth** [comment]
One way to test this is to try to load the array module every time we get a connection from the pool and see if this error goes away.

**Comment by igamigo** [comment]
Pretty sure the error is that only one connetion from the pool was being initialized instead of all of them in the code that @bobbinth referenced, which would explain the randomness. Created #132 which I think fixes it, but I didn't test too extensively yet.
