### ISSUE TITLE
Implement support for on-chain notes

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#141]
Currently, the node can handle only off-chain notes. To support on-chain notes we'd need to do the following:

1. Add necessary tables to the store database to store on-chain note info.
2. Update block producer to make sure it extracts on-chain note data from proven transactions and send this data to the store via `apply_block`.
3. Update the store to record the on-chain note data in the DB.
4. Update the store and the RPC to provide an endpoint for users to retrieve on-chain note details
  a. Maybe also update `sync_state` endpoint to return on-chain note details for such notes (though, this requires a bit more thinking).

This work requires https://github.com/0xPolygonMiden/miden-base/issues/403 to be completed.

**Comment by hackaugusto** [comment]
For some context:

related issues in miden-base: https://github.com/0xPolygonMiden/miden-base/issues/403 https://github.com/0xPolygonMiden/miden-base/issues/402
related PRs so far: https://github.com/0xPolygonMiden/miden-base/pull/481 https://github.com/0xPolygonMiden/miden-base/pull/485

**Comment by Dominik1999** [comment]
We break it down into smaller issues @hackaugusto @Dominik1999 

- issue to create an endpoint
- issue for DB
- ...

**Comment by Dominik1999** [comment]
@bobbinth see comment above

**Comment by bobbinth** [comment]
I broke out points 1 and 4 into separate issues: #286 and #288. So, this issue is now only for points 2 and 3 of the original description. I think the order of implementation could be:

1. #288
2. #286 
3. And then this issue.
