### ISSUE TITLE
Implement support for on-chain accounts

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#142]
Currently, the node can handle only off-chain accounts. To support on-chain accounts we'd need to do the following:

1. Add necessary tables to the store database to store on-chain account info.
2. Update block producer to make sure it extracts on-chain account data from proven transactions and send this data to the store via `apply_block`.
3. Update the store to record the on-chain account data in the DB.
4. Update the store and the RPC to provide an endpoint for users to retrieve on-chain account details.

This work requires https://github.com/0xPolygonMiden/miden-base/issues/403 to be completed.

**Comment by hackaugusto** [comment]
For some context:

related issues in miden-base: https://github.com/0xPolygonMiden/miden-base/issues/403 https://github.com/0xPolygonMiden/miden-base/issues/402
related PRs so far: https://github.com/0xPolygonMiden/miden-base/pull/481 https://github.com/0xPolygonMiden/miden-base/pull/485

**Comment by polydez** [comment]
@bobbinth @hackaugusto @phklive, how do you think, should we add on-chain account details into the respond of `sync_state` endpoint? Now it returns just account hashes. As an alternative, we can implement different endpoint for account full state.

**Comment by polydez** [comment]
@bobbinth 
> 3. How would the client get either the full account state or the delta? And how could we determine what is better to send in a given situation? (i.e., in some cases sending the full account state may be cheaper than sending a set of all deltas).

We can merge all requested deltas into a single one, but I'm not sure if this would be better than sending all the deltas because of consuming more server resources for multiple merging operations.

**Comment by polydez** [comment]
I've implemented one single endpoint for getting the latest details for public account. I think, it's enough for now, but we should create separate issue(s) for storage/endpoints improvements.

**Comment by bobbinth** [comment]
> I've implemented one single endpoint for getting the latest details for public account. I think, it's enough for now, but we should create separate issue(s) for storage/endpoints improvements.

I think this is fine for now - but let's create a separate issue specifically for implementing the delta-based approach.
