### ISSUE TITLE
Avoid cloning of in-memory structs on `apply_block`

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#149]
Currently, we clone in-memory data structures before we apply changes to them (e.g., [see here](https://github.com/0xPolygonMiden/miden-node/blob/main/store/src/state.rs#L252)). This is done to make sure that the received changes result in a valid update before applying them.

While this works, it will probably get pretty expensive once we have more data in the chain. A better approach would be to compute the updates without cloning the data, then validate the changes, and then apply the updates. To enable this, https://github.com/0xPolygonMiden/crypto/issues/222 will need to be implemented first.

**Comment by bobbinth** [comment]
Once #528 is merged, we should be able to address this issue by using the new `compute_mutations()` and `apply_mutations()` method of the Sparse Merkle trees.

**Comment by polydez** [comment]
Resolved by https://github.com/0xPolygonMiden/miden-node/pull/532
