### ISSUE TITLE
Chain MMR and note consumption

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#152]
This is a tricky problem, found by @igamigo while working on the client. I'm going try to lay down the problems:

1. A block's MMR does not include itself, this is because
  a. The MMR is build with blocks as leaves
  b. Self reference does not work with hashing
2. A note must be at least 1 block old for it to be consumed, this is because:
  a. To consume a note, an inclusion proof is required
  b. The inclusion proof is done against the MMR
  c. Because of 2.b. and 1. a transaction consuming a note can not use its creation block as a reference
3. A note returned in a `sync` request can not be consumed without a subsequent request, this is because:
  a. The request return block which produces a note of interested
  b. Because of 2. this note can not be consumed and a new request to fetch a new block is necessary
4. A block returned by `sync` can not be tracked, this is because
  a. The PartialMMR requires a valid merkle path to track an item
  b. Because of 2. to run a transaction the block's MMR must be known, so that is returned by `sync`
  c. Because of 1. 4.a and 4.b the block can not be tracked

**Comment by bobbinth** [comment]
> * A block's MMR does not include itself, this is because
>   a. The MMR is build with blocks as leaves
>   b. Self reference does not work with hashing
> * A note must be at least 1 block old for it to be consumed, this is because:
>   a. To consume a note, an inclusion proof is required
>   b. The inclusion proof is done against the MMR
>   c. Because of 2.b. and 1. a transaction consuming a note can not use its creation block as a reference
> * A note returned in a `sync` request can not be consumed without a subsequent request, this is because:
>   a. The request return block which produces a note of interested
>   b. Because of 2. this note can not be consumed and a new request to fetch a new block is necessary

I think we can solve these in the transaction kernel. Specifically, in the prologue we can add the block header of the latest block to the MMR peaks, and treat the results as the MMR against which we need to authenticate the notes (this is also described in https://github.com/0xPolygonMiden/miden-base/issues/305#issuecomment-1794267314, I think).

**Comment by hackaugusto** [comment]
One possible fix, we could redefine the leaf values of a MMR, instead of the MMR's leaves being [`BlockHeader`s](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/block/header.rs#L22C1-L35C2), the MMR leaves could be just the hash of the chain state:

```rust
// It may be interesting to have other fields, here is just a sketch
pub struct State {
    // I think the block number is not necessary, since it is easily derived from the leaf pos
    block_num: u32,

    account_root: Digest,
    nullifier_root: Digest,
    note_root: Digest,

    // sub_hash may no longer be necessary, since the this is much smaller than BlockHeader
    sub_hash: Digest,
}
```

**Comment by hackaugusto** [comment]
Note About the tracking of the latest block:

At first I thought the API should return the MMR delta up-to-including the block itself, that would mean the MMR with the block itself already included. This is possible because the store has the block header, and it can create the up-to-date MMR, with the downside of this MMR may not being in a block yet (in the case the node is being synced to the chain tip). This is however odd, and would create the problem that the transaction can not be executed, because the tx kernel needs to chain mmr as referenced by the block

**Comment by igamigo** [comment]
> Note About the tracking of the latest block:
> 
> At first I thought the API should return the MMR delta up-to-including the block itself, that would mean the MMR with the block itself already included. This is possible because the store has the block header, and it can create the up-to-date MMR, with the downside of this MMR may not being in a block yet (in the case the node is being synced to the chain tip). This is however odd, and would create the problem that the transaction can not be executed, because the tx kernel needs to chain mmr as referenced by the block

When feeding transaction inputs to the executor, could we not build the Chain MMR with the latest update we got + manually adding the block hash with the merkle path? I'm not sure whether the merkle path includes all nodes needed to the peak. If that's possible no changes to the kernel would have to be made but we would have to revert to how the node returned deltas a couple weeks ago.





> > * A block's MMR does not include itself, this is because
> >   a. The MMR is build with blocks as leaves
> >   b. Self reference does not work with hashing
> > * A note must be at least 1 block old for it to be consumed, this is because:
> >   a. To consume a note, an inclusion proof is required
> >   b. The inclusion proof is done against the MMR
> >   c. Because of 2.b. and 1. a transaction consuming a note can not use its creation block as a reference
> > * A note returned in a `sync` request can not be consumed without a subsequent request, this is because:
> >   a. The request return block which produces a note of interested
> >   b. Because of 2. this note can not be consumed and a new request to fetch a new block is necessary
> 
> I think we can solve these in the transaction kernel. Specifically, in the prologue we can add the block header of the latest block to the MMR peaks, and treat the results as the MMR against which we need to authenticate the notes (this is also described in [0xPolygonMiden/miden-base#305 (comment)](https://github.com/0xPolygonMiden/miden-base/issues/305#issuecomment-1794267314), I think).
> 
> The cost of doing this is a single extra MMR update, which I think may be as high as a few hundred cycles. Not great, not terrible :)

I am not sure but I think this would also entail some changes to how `PartialMmr` allows to be constructed right now: If I want to consume a note from block $N$, I have to construct the `PartialMmr` from the peaks that I got as a response from the node, which are the ones related to `PartialMmr` from block $N-1$. I have no way of adding and tracking the block as a leaf to the Chain/PartialMmr that I feed to the executor because the block hash belongs to a forest which is higher than the `PartialMmr` that I have

**Comment by hackaugusto** [comment]
Possible approach to fix the tracking of a block:

We could change the definition of `state_sync`, instead of returning the block which contains notes of interest, to return the next block. That is to say, if block `n` create notes with a tag requested by the client, then the server would return the block header of `n+1`, and a merkle path for block `n`. This has two issues:

- To bootstrap a client, it would not only need all the data of the genesis https://github.com/0xPolygonMiden/miden-node/issues/153 , but also the block header `1`
- If there is a note that matches the tag at the chain tip, it can not be returned, because there is no next block to use in the reply

**Comment by hackaugusto** [comment]
> When feeding transaction inputs to the executor, could we not build the Chain MMR with the latest update we got + manually adding the block hash with the merkle path? I'm not sure whether the merkle path includes all nodes needed to the peak. If that's possible no changes to the kernel would have to be made but we would have to revert to how the node returned deltas a couple weeks ago.

Lets see, by definition, the returned block header is the right most in the MMR, since it is the latest block added to it, and the MMR is append-only. We can learn a few things from the merkle path:

- If the path is empty, then we have an odd number of block headers, and the block height must be even (because it is 0-indexed).
- If the path is non-empty, then the merkle path must contain only left siblings. And these are by definition the previous peaks.

So I think you're right, we can reconstruct the MMR peaks for `n-1` from the peaks of `n` + its merkle path. Not sure if this is the easiest approach, but to me it seems it works (would still write quite a few tests though :) )

**Comment by hackaugusto** [comment]
> I think we can solve these in the transaction kernel. Specifically, in the prologue we can add the block header of the latest block to the MMR peaks, and treat the results as the MMR against which we need to authenticate the notes (this is also described in https://github.com/0xPolygonMiden/miden-base/issues/305#issuecomment-1794267314, I think).

Just to clarify, you mean computing the MMR which includes the current block header in the prologue, and using it instead of the block's chain root?

**Comment by bobbinth** [comment]
Assuming we don't modify the structure of chain MMR as @hackaugusto suggested in https://github.com/0xPolygonMiden/miden-node/issues/152#issuecomment-1894522614 (this may have its own merits, but I'll need time to think it through). The transaction kernel would work as follows:

1. The inputs into the transaction would be block header $N$ and chain MMR with $N$ leaves. That is `block_header.chain_root==chain_mmr.hash_peaks()`.
2. In the prologue, we would take the block header and add it to the chain MMR getting chain MMR with $N + 1$ leaves. That is, the block header $N$ would be the rightmost leaf.
  a. This would allow us authenticating notes created in block $N$ against this chain MMR.
3. For 2 to work, we'd need to make sure that the advice provider contains all the right paths for chain MMR with $N+1$ leaves - but I think that should be pretty straight forward: we add the new block to chain MMR outside of the VM, and use authentication paths from this chain MMR in the advice provider.
  a. We probably will need to add a new method on `PartialMmr` which would allow adding a single leaf to it - something that does the work equivalent to `Mmr::add()`.

From transaction kernel standpoint, I think this should all work. Still thinking through the sync aspect of it.

**Comment by bobbinth** [comment]
> Just to clarify, you mean computing the MMR which includes the current block header in the prologue, and using it instead of the block's chain root?

Yes, exactly. One question that I have is whether this update will naturally result in updated authentication paths in the advice provider (probably not?), or we'd need to update the Chain MMR outside of the VM as well to get the authentication paths for the new chain MMR (this is what I described in the previous comment).

**Comment by bobbinth** [comment]
Here are a few thoughts on syncing:

First, when the client starts out, we should probably insert the block header of the genesis block into its database. In the future, we could do it via config files, but for now I think the simplest thing is to make a `GetBlockHeaderByNumber(0)` request. At this point, chain MMR tracked by the client would be empty.

Then, the client would start making `sync` requests to the node. The first request would have `block_num=0`, and in general, the client should make requests with the last known block number.

Let's say the node is currently on block 5 (i.e., there are 6 blocks in the chain). It would respond with MMR delta with forest values `(request.block_num, last_block.block_num)` - or in our example `(0, 5)`. This is actually what we do [now](https://github.com/0xPolygonMiden/miden-node/blob/main/store/src/state.rs#L356). However, for `block_path`, the node would respond with a path for `request.block_num` at chain MMR forest value set to `last_block.block_num` - in our example this is also `(0, 5)`. This is different fro what we do [now](https://github.com/0xPolygonMiden/miden-node/blob/main/store/src/state.rs#L358).

The client, upon receiving this response would do the following:
1. Apply the received MMR delta to the local chain MMR. In our example, this will bring it to `forest=5`.
2. If the block for the requested `block_num` had notes the client is interested in, the client would also add the received `block_path` to the chain MMR.

The last point is different from how it works now. Specifically, the client would need to track info about whether a given block contains notes of interest. One way to do this could be to add `has_notes` field to the `block_headers` table. This field would be set at the time when the block header is inserted into the table.

For the second `sync` request, the client would use `block_num=5`, and the above process would be repeated. For example, if the node is now at block 6 (i.e., there are 7 blocks in the chain), the node would return:
- block header for block `6`.
- MMR delta for `(5, 6)`.
- `block_path` for `(5, 6)`.

If I thought this through correctly, this will ensure that the client always has consistent view of the chain - i.e., for block $N$, the local chain MMR will have `forest` set to $N$ as well. That is, `block_header.chain_root==chain_mmr.hash_peaks()`. And assuming the modification to the transaction kernel I mentioned in https://github.com/0xPolygonMiden/miden-node/issues/152#issuecomment-1894635292, the client should be able to execute transactions against the latest block.

**Comment by bobbinth** [comment]
The kernel changes described above are in https://github.com/0xPolygonMiden/miden-base/pull/421.

**Comment by bobbinth** [comment]
A potentially better approach is to get rid of `block_path` entirely. The process would then work as follows:

The node builds the MMR delta as `(request.block_num + 1, last_block.block_num)` rather than `(request.block_num, last_block.block_num)` as suggested in one of the above comments. This will require special handling for cases when `request.block_num == last_block.block_num` - but I don't think that's a big problem (and we should probably have this check anyway).

Then, the client does the following:
1. First, add the the current block header to the local MMR.
2. Then, apply the MMR delta from the node's response.

For the first point, we'd use something similar to [ChainMmr::add_block()](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/transaction/chain_mmr.rs#L98), which might be a good thing to have on `PartialMmr` anyway.
