### ISSUE TITLE
Determine the semantics of `block_num` in the `SyncState`

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#153]
The main question is:

- Is the `block_num` the last block know by the client, or
- Is the `block_num` the first block _unknown_ by the client

After a call with @igamigo my understanding is that the client is using the second meaning, because the client does not know the genesis block, and the mmr update includes it.

**Comment by hackaugusto** [comment]
IMO this is not great, because it means the client doesn't have a truth base built in, and has to trust the server.

I think we should have the genesis built-in the client, as ground truth, to prevent man-in-the-middel attacks.

**Comment by bobbinth** [comment]
Does the client actually use `GetBlockHeaderByNumberRequest`? I thought it relies only on the `SyncState` request.

For `SyncState` requests, I think it should be the first option - `block_num` should be the last block known by the client.

I think it may be a good idea to include genesis block hash into the client during build - but we should discuss pros and cons of it. For now, we could actually just use `GetBlockHeaderByNumberRequest` with parameter `0` to get the genesis block header.

**Comment by hackaugusto** [comment]
> Does the client actually use GetBlockHeaderByNumberRequest? I thought it relies only on the SyncState request.

Ah, my bad, it is `SyncState`, I copied the wrong message in the issue title. Updated it.

**Comment by igamigo** [comment]
This might be a bug on the client, but the default sync state request is sent with 0 as `block_num` (the field is `u32`) and the delta is applied to a blank Mmr (`MmrPeaks::new(0, vec![])` and then `PartialMmr::from_peaks()`). Subsequent requests are sent with whatever `block_num` you got as a response in the previous sync state request.

**Comment by hackaugusto** [comment]
The `block_num` has been defined as the latest block known by the client. So the response start at `block_num+1`
