### ISSUE TITLE
Add `notes` and `nullifiers` to `genesis.toml`

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#154]
We have the need to be able to pass a configuration file on node initialisation to pre-populate the DB ( store ) of the node with:
- Notes
- Nullifiers

This would be helpful for testing, but also potentially in production with nodes that would want to init from a certain state.

Depends on: #138 
Linked to: #127

**Comment by bobbinth** [comment]
Closing this as I don't think we need to implement this functionality any more.
