### ISSUE TITLE
Remove of `num_assets` from note metadata

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-node#169]
https://github.com/0xPolygonMiden/miden-base/pull/414 removed `num_assets` field from the `NoteMetadata` struct. This will break some things in `miden-node` (and `miden-client`). So, before we can merge this PR in `miden-base` we should update `miden-node` to account for this change.

The changes will probably include:
- Updating protobuf messages and related conversions.
- Removing `num_assets` from the `notes` table in the store and updating related SQL statements and functions.

**Comment by bobbinth** [comment]
Description updated.
