### ISSUE TITLE
Verification fails for transactions from new accounts

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#176]
While testing the client, I'm trying to send transactions to the node with new accounts (in this case, creating a note with assets from a fungible faucet). Local execution works fine, but when submitting the proof to the node I'm getting this:

```
rpc api error: rpc request failed for submit_proven_transaction: status: InvalidArgument, message: "VerificationFailed(IncorrectAccountInitialHash { tx_initial_account_hash: RpoDigest([7804508306418852326, 6348915401079023739, 4425441608650618110, 7471845003988793641]), store_account_hash: Some(RpoDigest([0, 0, 0, 0])) })", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "content-length": "0", "date": "Wed, 24 Jan 2024 16:05:19 GMT"} }
```

Looks like the node checks the account's hash and because it has a blank hash for new accounts, it never validates.

**Comment by phklive** [comment]
@igamigo will look into it, interestingly the verification of proofs also fail when sending a `ProvenTransaction` from the client to the node. 

I am working on adding the proof verification on the node `RPC` and `Block Producer` in this PR: https://github.com/0xPolygonMiden/miden-node/pull/171

**Comment by phklive** [comment]
For now this is the error that we are getting when trying to verify a proof from the client on the node.

<img width="629" alt="SCR-20240126-muup" src="https://github.com/0xPolygonMiden/miden-node/assets/42912740/902a89c6-76bb-4efd-a639-a553da130ebf">

**Comment by igamigo** [comment]
Is that by using accounts that are not in the genesis state, or by importing the accounts beforehand (or maybe it happens in both scenarios)?

**Comment by phklive** [comment]
> Is that by using accounts that are not in the genesis state, or by importing the accounts beforehand (or maybe it happens in both scenarios)?

By importing accounts beforehand and making a tx, sending it to the running node and trying to verify the proof. 

In this PR: #171

**Comment by phklive** [comment]
Added a verifier with 96 min_security in the miden_client for testing just after the proof is executed. It errors out. That rules out the possibility of error in the message transmission, serialisation / deserialisation.

```rust
Verif error: TransactionVerificationFailed(
    VerifierError(
        InconsistentOodConstraintEvaluations,
    ),
)
```

**Comment by bobbinth** [comment]
I think these are two separate issues: this issue is pretty simple to fix and is not related to proof verification. The proof verification issue is a puzzle that we still need to solve - but I suspect it is something simple (i.e., a mismatch somewhere).

**Comment by phklive** [comment]
I have been able to reproduce the error and understand the flow and why it is happening.

What should be the correct behaviour in this situation? Should the unknown account be added to the store?

**Comment by igamigo** [comment]
Created an account from the client with `account new` (`./miden-client account new basic-immutable`)

**Comment by bobbinth** [comment]
So, there are two flows here one of which is not being handled correctly:

1. An existing account is updated: before updating the hash of this account in the account tree/table we need to make sure the previous state was consistent with what was specified in the update. This case is currently working fine.
2. A new account is created: here, we cannot perform the check mentioned above because account tree/table has the initial state set to `[ZERO; 4]` for non-existent accounts. So, we need to make an exception and in case we are inserting a new account, check that the current state recorded in the DB is `[ZERO; 4]` and if it is, insert the account.

**Comment by phklive** [comment]
Understood. While looking at the code used to insert new accounts in the DB I see that the only way for now would be to use the `apply_block` function right? 

https://github.com/0xPolygonMiden/miden-node/blob/5e811a1ffa200f23cd72fa17041502ecb1ea3b05/block-producer/src/state_view/mod.rs#L96-L129

I don't fully understand why we would want to add the account at this point in time? 

Shouldn't we wait for the account to be added when the tx has been added in a block and applied to the DB?

**Comment by bobbinth** [comment]
> Understood. While looking at the code used to insert new accounts in the DB I see that the only way for now would be to use the `apply_block` function right?

Yes - `apply_block` is the only way to update the store. This part is working correctly and we don't need to change anything there, I think. The part that needs to change is the check in the transaction verifier in the block producer.

> I don't fully understand why we would want to add the account at this point in time?
> 
> Shouldn't we wait for the account to be added when the tx has been added in a block and applied to the DB?

I'm not sure I fully understood the question, but `self.store.apply_block()` (line 105) adds the new block to the store. From that point on, the store has already been updated - the rest is just synchronizing the in-memory objects of the bock producer with the new block.

**Comment by phklive** [comment]
My understanding is the following: 
1. User grinds new account locally
2. Submits tx to the network
3. Node picks up tx, batches it, block is created ( There are also proofs involved, skipping for simplicity )
4. Node uses `apply_block` to update the store with the latest block updating the `block_header`, `accounts`, `notes`, `nullifiers` tables in the DB

Does that seem correct as a mental model? 

Hence what I understand is that to add an account to the DB we wait for it's tx to get into a block that is applied to the DB through `apply_block` correct?

**Comment by phklive** [comment]
> My understanding is the following:
> 
> 1. User grinds new account locally
> 2. Submits tx to the network
> 3. Node picks up tx, batches it, block is created ( There are also proofs involved, skipping for simplicity )
> 4. Node uses `apply_block` to update the store with the latest block updating the `block_header`, `accounts`, `notes`, `nullifiers` tables in the DB
> 
> Does that seem correct as a mental model?
> 
> Hence what I understand is that to add an account to the DB we wait for it's tx to get into a block that is applied to the DB through `apply_block` correct?

My understanding is the following:

User grinds new account locally
Submits tx to the network
Node picks up tx, batches it, block is created ( There are also proofs involved, skipping for simplicity )
Node uses apply_block to update the store with the latest block updating the block_header, accounts, notes, nullifiers tables in the DB
Does that seem correct as a mental model?

Hence what I understand is that to add an account to the DB we wait for it's tx to get into a block that is applied to the DB through apply_block correct?

**Comment by bobbinth** [comment]
> Does that seem correct as a mental model?
> 
> Hence what I understand is that to add an account to the DB we wait for it's tx to get into a block that is applied to the DB through `apply_block` correct?

Correct. This issue is not so much about the store though. Before accepting a transaction from the user, we check if the transaction would result in a valid update. For example, If the transaction is updating account from state `a` to state `b`, but the current account state is not `a`, this transaction is not valid and the node would not even consider it for batching etc.

**Comment by phklive** [comment]
If so then the only problem that we have here is that the check is not considering the case where the `account_hash` contained in the DB for the `account_hash` of the received tx is equal to `Digest::default()`. 

If we just add this condition it should fix the error.

Where we might have not understood each other @bobbinth is the moment you said: 

 > So, we need to make an exception and in case we are inserting a new account, check that the current state recorded in the DB is [ZERO; 4] and if it is, insert the account.
 
 When you said `insert the account` I understood that you wanted to immediately add the account to the DB ( could be by using a new rpc call ) which I don't think is necessary because it's done after performing all checks, batching, blocking and block applying.

**Comment by bobbinth** [comment]
> > So, we need to make an exception and in case we are inserting a new account, check that the current state recorded in the DB is [ZERO; 4] and if it is, insert the account.
> 
> When you said `insert the account` I understood that you wanted to immediately add the account to the DB ( could be by using a new rpc call ) which I don't think is necessary because it's done after performing all checks, batching, blocking and block applying.
> 
> Am I clear? (let me know if not) are we agreeing?

Yes - sorry for not being precise here. We should make sure a transaction which is executed against a new account can get processed correctly using existing flows. So, no new RPC calls or ways to modify the DB are needed.

Currently this is prevented by the checks in transaction verifier and maybe something else (e.g., maybe there are additional checks during block building and `apply_batch` which I'm not taking into consideration here).

**Comment by phklive** [comment]
![SCR-20240201-khhm-2](https://github.com/0xPolygonMiden/miden-node/assets/42912740/923a9711-5149-4dfc-9f75-4a99db625374)

Fixed.
