### ISSUE TITLE
Allow multiple in-flight transactions for an account.

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#186]
Currently for simplicity only one transaction can be in-flight per account.

**Comment by hackaugusto** [comment]
Btw, what is the reason for this constraint? Is it just because the code is simpler? Or do we actually want to limit the concurrent in-flight transaction to 1 in the beginning? (I'm asking because it seems to lift this is pretty straightforward)

**Comment by bobbinth** [comment]
> Btw, what is the reason for this constraint? Is it just because the code is simpler?

Yep - just made the code a bit simpler at the time when there were a lot of moving parts.

**Comment by bobbinth** [comment]
Some parts of discussions in #191 and #196 may be relevant here.

**Comment by bobbinth** [comment]
Also, #235 could also be good background info.

**Comment by bobbinth** [comment]
Closed #407.
