### ISSUE TITLE
Remove block producer's Store trait

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#196]
The `Store` trait abstracts over the gRPC server, the main utility of this trait is to implement tests. However, this is not necessary, since tonic already has a strategy to mock the servers for testing, here is an example:

https://github.com/hyperium/tonic/blob/master/examples/src/mock/mock.rs

**Comment by bobbinth** [comment]
Would we basically just replace `Store` trait with the current `DefaultStore` struct? (i.e., `Store` trait goes away and `DefaultStore` struct becomes `Store` struct).

If we can do this while still mocking store for test purposes, I'm in favor or that (upon a quick look at the example, I didn't quite understand how it would work, but I also didn't look too long).

**Comment by hackaugusto** [comment]
Implementation wise it would something like this:

- [`Store`](https://github.com/0xPolygonMiden/miden-node/blob/d81d3c18aa9abb3ba67872114ad0e6c63b854ac4/block-producer/src/store/mod.rs#L28-L42) trait is removed
    - This issue is not about `ApplyBlock`, that would stay there as far as this issue is concerned
- The existing [`impl Store for DefaultStore`](https://github.com/0xPolygonMiden/miden-node/blob/d81d3c18aa9abb3ba67872114ad0e6c63b854ac4/block-producer/src/store/mod.rs#L113-L120) would become just an `impl DefaultStore`, as this code is doing some extra object translation.
- The [`MockStoreSuccess`](https://github.com/0xPolygonMiden/miden-node/blob/main/block-producer/src/test_utils/store.rs#L156-L157) and [`MockStoreFailure`](https://github.com/0xPolygonMiden/miden-node/blob/main/block-producer/src/test_utils/store.rs#L241-L242) would be rewritten, and implemented in [terms of trait](https://github.com/0xPolygonMiden/miden-node/blob/d81d3c18aa9abb3ba67872114ad0e6c63b854ac4/proto/src/generated/store.rs#L304-L324) for the [gRPC store interface](https://github.com/0xPolygonMiden/miden-node/blob/d81d3c18aa9abb3ba67872114ad0e6c63b854ac4/proto/proto/store.proto#L10-L20)
     - The [linked example](https://github.com/hyperium/tonic/blob/master/examples/src/mock/mock.rs) shows how this can be used. Basically the test spawns a task to run the test server, and uses a stream instead of a socket to do the communication.
- And if you want, the `DefaultStore` struct can be renamed to `Store`

**Comment by bobbinth** [comment]
Makes sense. Yes, I think this works. @plafer what do you think?

**Comment by plafer** [comment]
The one downside is that it makes it harder to move away from gRPC in the future. But if that's not much of a concern, then yes this approach is simpler and thus better.

**Comment by plafer** [comment]
I'm just remembering previous conversations we had about how when all components are running in the same process (including the database and rpc), we shouldn't need to use gRPC. This change would force us to keep using gRPC in that situation.

**Comment by hackaugusto** [comment]
> The one downside is that it makes it harder to move away from gRPC in the future. But if that's not much of a concern, then yes this approach is simpler and thus better.

This is a far point. But I think changes like this happen once or twice in a project's lifetime. So personally I would optimize for easy of readability here.

> I'm just remembering previous conversations we had about how when all components are running in the same process (including the database and rpc), we shouldn't need to use gRPC. This change would force us to keep using gRPC in that situation.

This is true, we probably don't need the socket api, but we would need to do something similar to what is done in the tests, and communicate over a channel.

**Comment by Mirko-von-Leipzig** [comment]
Closed in #571
