### ISSUE TITLE
Make Genesis returns error if no accounts are imported

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#198]
When running the `make-genesis` command on the miden-node if no accounts are present in the genesis.toml genesis input file an error is returned by the CLI: 

```bash
Error: Failed to load node/genesis.toml genesis input file: missing field `accounts`

OR 

Error: Failed to load node/genesis.toml genesis input file: missing field `type` for key "default.accounts.0" in node/genesis.toml TOML file
```

**Goal of this issue**: Fix this behavior and enable the generation of a genesis file without accounts

**Comment by polydez** [comment]
Resolved by https://github.com/0xPolygonMiden/miden-node/pull/420
