### ISSUE TITLE
Change default config file path to `miden-node.toml`

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#205]
Currently, the default config file is `miden.toml`. This conflicts with `miden.toml` that miden client also uses as a default config file (see https://github.com/0xPolygonMiden/miden-client/issues/133). I think we should change the default to `miden-node.toml`.

**Comment by phklive** [comment]
What do you think of: 
- Client => `client.toml`
- Node => `node.toml`

It's the main configuration file hence making sense to have the same name as the crate. The redundant use of `miden`  doesn't really add value here.
