### ISSUE TITLE
Rename `note_hash` to `note_id` on `NoteSyncRecord`

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#206]
After a recent `Note` refactor,  the field `note_hash` was deprecated and changed into a `note_id` field. In the node's RPC however, [the `NoteSyncRecord` still uses the old terminology](https://github.com/0xPolygonMiden/miden-node/blob/c4344cb837199f468bbf442faac35c80cb5d70d7/proto/proto/note.proto#L19) although it is set to the correct value.

**Comment by bobbinth** [comment]
@polydez - this could be done as a part of #74.
