### ISSUE TITLE
`NullifierInputRecord`: Add `Smt` leaf

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#210]
#209 is currently blocked because the block producer needs 1 more piece of information: the leaf pre-image for all leaves that are being updated (in order to run `smt::set`).

`NullifierInputRecord` would need to look something like:

```rs
pub struct NullifierInputRecord {
    pub nullifier: Digest,
    pub proof: MerklePath,
    pub smt_leaf: Vec<(Digest, Word)>,
}
```

where `smt_leaf` is populated using `SmtLeaf::into_entries()`.

**Comment by bobbinth** [comment]
This is related to https://github.com/0xPolygonMiden/crypto/issues/251. Ideally, we'd have something like an `SmtOpening` struct which looks like so:
```Rust
pub struct SmtOpening {
    path: MerklePath,
    entries: Vec<(RpoDigest, Word)>,
}
```
And then `NullifierInputRecord` would become:
```Rust
pub struct NullifierInputRecord {
    pub nullifier: Digest,
    pub opening: SmtOpening,
}
```
