### ISSUE TITLE
Improve variants of `ApplyBlockError` in store

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/miden-node#214]
From @bobbinth:

> Let's create an issue to revisit variants of this error. I think we can consolidate and normalize them a bit better than how they are now.

**Comment by bobbinth** [comment]
I think there are a few things to improve with the `ApplyBlockError`:

1. We have a bunch of error variants which are really about inconsistent inputs - e.g., `NewBlockInvalidBlockNum`, `NewBlockInvalidPrevHash` etc. I think these should be treated separately and the store should not report "internal error" in case of such errors.
2. We also have a similar situation for invalid inputs - e.g., `ConversionError`, `InvalidAccountId`, `DuplicatedNullifiers`. Some of these will probably go away after we fix the domain objects organization.
3. We have a generic `DatabaseError` but I think it is used only in one place - and if so, we can make it into a more concrete error type.

But going back to the first point, the main thing is that we should be able to better distinguish between the situations when the request is invalid in some way or if the error happened somewhere in the store.
