### ISSUE TITLE
Set up a Miden node with Polygon DevOps team

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-node#221]
In order to let ppl use Miden, we need a remote node deployed, see https://0xpolygonmiden.github.io/miden-base/introduction/getting-started.html

We already reached out to the DevOps team and got the following information

## Notes from the first call
@hackaugusto thanks for the notes.

To summarize the meeting we had with the dev ops. These are the things that they need to get started:
- preffered cloud service, e.g. aws or gcp?
- preferred OS, e.g. ubuntu, centos, fedora, etc
- preffered cpu arch, x86, arm, etc.
- how will this be packaged? containers? distro packages?
- hardware requirements? how much disk? how much IOPS? how much RAM? how much network? GPU?
- how will be the healthchecking done? initial suggestion. was warp
- Fill their ToDo list https://www.notion.so/polygontechnology/Project-Deployment-Readiness-Checklist-50744458a9df46deb218ec377c200bdb

### Our answers
![Image](https://github.com/0xPolygonMiden/miden-node/assets/35031754/291b8784-ca03-47fa-803f-b95e75846afa)

### Additional notes
In addition, there were some notes the team dropped, to make sure things work smoothly:
- please communicate how the packaging will be done, so they can prepare it if a distro packaged is required
- make sure all configuration nobs are exposed, at least via the configuration file (i.e. no hard coded constants)
- their end goal would be to have a CI/CD setup, so we would not have access keys, and instead the CI would get a temporary access token to do the deployment
- they do have a standard for servers, which is a suite of packages they are used to. We need to learn what these are to do our metrics
- they need to know how the healthchecking will be done, that is attached to the way the software is deployed, and we need to answer the packaging question above, because that affects the healthchecking
- they noted that containers may have IOPS limits, that starts to be an issue around 1TB of data

## Feedback from the DevOps team on our issues
We want to DevOps team to give us feedback to the following issues: 

- https://github.com/0xPolygonMiden/miden-node/issues/144
- https://github.com/0xPolygonMiden/miden-node/issues/95
- https://github.com/0xPolygonMiden/miden-node/issues/93
- https://github.com/0xPolygonMiden/miden-node/issues/91
- https://github.com/0xPolygonMiden/miden-node/issues/83

## Next steps
- [x] Open a Jira Ticket (https://polygon.atlassian.net/servicedesk/customer/portal/5/DEVOPS-2527)
- [ ] Work on their ToDo list 
- [ ] Support their deployment

## Timeline
I need a stable remote Miden Node for our workshops in Denver. To have buffer, can you please ensure we have something running Thursday 22th Feb?

**Comment by Dominik1999** [comment]
This also seems to be completed?

**Comment by phklive** [comment]
Yes, done.
