### ISSUE TITLE
Accounts created with `make_genesis` command have nonce 0

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#223]
We define as `new accounts` accounts with a nonce of 0. 

An account that has a nonce of 0 should not be stored in the DB considering that it has never created a tx and hence has never been able to interact with the rollup to end up in the DB. 

We need to fix the way we create accounts through the `make_genesis` function to make sure they have nonce = 1.

https://github.com/0xPolygonMiden/miden-node/blob/db51f392257abcf2fd5a703a15b830e4d8a5f7ab/node/src/commands/genesis/mod.rs#L44

**Comment by phklive** [comment]
This issue has been discussed here: https://github.com/0xPolygonMiden/miden-client/issues/139

The following situation arises:

- We have updated the way we create `ProvenTransaction` in miden-base hence passing `Digest::default()` as `init_account_hash` when the account is new ( nonce 0 )

- Accounts created via `make_genesis` function are added automatically to the DB even though they have never interacted with the DB. Hence they have an `init_account_hash` that is not `Digest::default()` stored in the DB at genesis

- When wanting to make a tx with an account that was created at genesis by importing them into a client it errors out with the following error: 
```
rpc api error: rpc request failed for submit_proven_transaction: status: InvalidArgument, message: "VerificationFailed(IncorrectAccountInitialHash { tx_initial_account_hash: RpoDigest([0, 0, 0, 0]), store_account_hash: Some(RpoDigest([2194417484513961168, 8441993850887968501, 2612373643818268576, 12735460985696479504])) })", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "content-length": "0", "date": "Tue, 13 Feb 2024 10:00:16 GMT"} }
```

- The constraint check fails because the `init_account_hash` in the `ProvenTransaction` is `Digest::default()` ( considering the account is new ) but it is not `Digest::default()` in the Nodes store, hence erroring out.

Some ways to solve this  could be:
- initialise the accounts with nonce of 1 ( Not sure if that is possible without executing a tx )
- Not import the accounts in the nodes DB but wait for a tx
- Not import the accounts in the nodes DB but automatically make 2 tx's adding the accounts into the db

**Comment by bobbinth** [comment]
> initialise the accounts with nonce of 1 ( Not sure if that is possible without executing a tx )

I think this is the way to go. The current `create_basic_fungible_faucet()` etc. functions create accounts with the nonce set to $0$ - so, I think we have 2 options here:
1. Modify the functions to specify whether an account should be created with nonce $0$.
2. Add `Account::set_nonce()` (or something similar) method and then modify the account manually after it is created.

I'm leaning towards the second option.

**Comment by phklive** [comment]
Two questions regarding a potential `Account::set_nonce()` function: 

- Couldn't it be dangerous to have a function that could update the nonce of an account without going through a valid transaction? 

- When updating the nonce for an account should it usually increases only 1 by 1 or in MIden could it increase by for example 5 at once? If not should we make the function `increment_nonce` instead of `set_nonce`?

**Comment by bobbinth** [comment]
> Couldn't it be dangerous to have a function that could update the nonce of an account without going through a valid transaction?

We already have functions which can mutate the account state directly (e.g., `apply_delta()`) - so, this function doesn't change anything. In general, I think it is OK to have these types of mutators because updating account state may be needed for a variety of reasons - but yes, usually, it would be done as a result of executing a transaction.

> When updating the nonce for an account should it usually increases only 1 by 1 or in MIden could it increase by for example 5 at once? If not should we make the function `increment_nonce` instead of `set_nonce`?

Incrementing nonce by more than 1 could be useful in the context of multi-sig transactions, though, the exact mechanism of how this will be used is till TBD. At the transaction kernel level, we do restrict nonce increments to be at most $2^{32}$ (i.e., a single transaction can increment the nonce by at most $2^{32}$). But I don't think we need to impose a similar limit on the Rust side.
