### ISSUE TITLE
Change `timestamp` type to `fixed32`

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/miden-node#236]
Currently we use `uint64` type for `timestamp` field of `BlockHeader` structure: https://github.com/0xPolygonMiden/miden-node/blob/78e5f5bb5e6c9da86bcf783ffc05aecb8f1d832c/proto/proto/block_header.proto#L26

I think, we decided to make this field 64-bit wide, because we store milliseconds since Linux epoch into it and 32 bits is not enough. But do we really need to store milliseconds in block timestamp, since we produce one block per several seconds?

Consider converting `timestamp` field type to `fixed32`.

> Let's create an issue to consider converting `timestamp` to `u32` in the future.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-node/pull/226#pullrequestreview-1878257039_

**Comment by bobbinth** [comment]
I'm not seeing any downsides to storing seconds instead of milliseconds.

**Comment by polydez** [comment]
Resolved in https://github.com/0xPolygonMiden/miden-base/pull/639
