### ISSUE TITLE
Endpoint to retrieve block proposal

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#24]
When the block producer is ready to produce a new block, it needs an endpoint to request the transaction batch data from the memory pool.

```[tasklist]
### Tasks
- [ ] Add protobuf message describing the transaction batch
- [ ] Add an endpoint to the mempool to be requested by the block producer.
```

**Comment by bobbinth** [comment]
Closing as this is no longer relevant in the current design.
