### ISSUE TITLE
Reproducible Build

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#251]
- [ ] use `cargo make`
- [ ] add `Cargo.lock` to repo
- [ ] add `rust-toolchain.toml`
- [ ] update ci to use `cargo make` rules
- [ ] update CONTRIBUTING.md to mention `cargo make`
- [ ] update `pre-commmit.yaml` to use `cargo make`

ref: https://github.com/0xPolygonMiden/miden-vm/issues/1259

**Comment by hackaugusto** [comment]
related: https://github.com/0xPolygonMiden/miden-node/issues/238

**Comment by phklive** [comment]
@hackaugusto could you give me more information on what we would need to add to the `rust-toolchain.toml`?

**Comment by hackaugusto** [comment]
Ofcourse. The [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) allows us to define the compiler version we are testing/build with. The goal is for every build to use the same compiler version, including your local builds and the CI, this will remove build differences because of compiler version differences.

In our case we want to define the following:

- A stable version of the compiler. Which should match the minimum `rust-version` used for all crates in the repo. This will test the minimum supported rust version (MSRV)
     - In some cases this will also need the wasm32 target, for the crates that we support `no-std`.
- A nightly version of the compiler. This is mostly used because of `cargo fmt`, because we use nightly format features

**Comment by phklive** [comment]
After doing some research and testing I have not found a way to set both the stable and nightly versions in a rust-toolchain.toml file.

I propose the following solution, we use the toolchain file to set the stable version for all crates of the node and use cargo make setting the right flags to run fmt and clippy using nightly. 

It works well.

**Comment by hackaugusto** [comment]
> @hackaugusto we do not have a pre-commit.yaml file in the miden-node for now right? Should we add one?

Go ahead :)
