### ISSUE TITLE
Add next branch to miden-node repo

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#258]
As we are doing with the other repos of Miden it would be ideal to add a next branch to miden-node to prepare for new releases.

Example: https://github.com/0xPolygonMiden/crypto/tree/next

**Comment by hackaugusto** [comment]
https://github.com/0xPolygonMiden/miden-node/tree/next

**Comment by bobbinth** [comment]
I made both `main` and `next` write-protected. I'm keeping the `main` as the base branch for now (as this is the current "stable" code and that's the methodology we use in other places).
