### ISSUE TITLE
Add a wrapper type for the note position

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#276]
### Node's components affected by this task

- [X] RPC
- [X] Block producer
- [X] Store
- [X] Protobuf messages
- [X] Testing

### What should be done?

Make the code more robust to errors due to invalid handling of the `node_idx`. The `NoteSmt` has a very particular shape. The even indexes hold a commitment to the note, and the odd indexes hold a commitment to the note's metadata, whereas the note_idx is the id of the parent node.

### How should it be done?

Add wrapper types to prevent mixing different value domains. 

### When is this task done?

When the confusion is removed and the code is more resilient. This should probably also touch the miden-base and miden-client repos.

### Additional context

https://github.com/0xPolygonMiden/miden-node/commit/3c202e79425757e5e6be1b8cb6a1592e34ad723c
https://github.com/0xPolygonMiden/miden-client/issues/201#issuecomment-1989432215

**Comment by Dominik1999** [comment]
Nice Issue Template!

**Comment by bobbinth** [comment]
Once I'm done with refactoring of notes (which I've been working on for way too long), this may be quite a bit simpler as notes + metadata will be hashed sequentially and stored in a single leaf.

But I still think having a wrapper type for note tree is a good idea.
