### ISSUE TITLE
Implement `GetNotesById` endpoint

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#286]
Ability to retrieve notes by note ID could be useful for a couple of purposes:

1. Retrieve details of public notes.
2. Retrieve inclusion paths of off-chain notes.

The endpoint could take the following parameters:
- A list of note IDs.

The endpoint would return a list of note objects matching the specified IDs:
- For off-chain notes, the message would be pretty much identical to our current `Note` message.
- For public notes, this would also include all notes detailes to reconstruct the `Note` object (i.e., note script, note inputs, serial num).

A couple of open questions:
- Should we put a limit on the number of requested notes?
- Should this endpoint by a streaming endpoint?

**Comment by phklive** [comment]
Hello Bobbin, in your description you say: 

`The endpoint could take two parameters:` but you only list one, could you tell me what the second parameter should / could be ?

**Comment by phklive** [comment]
Why would you want to add a `streaming` capability to this endpoin?

**Comment by phklive** [comment]
This should be implemented on the RPC correct? We have 2 places where it could be implemented for now. RPC and Store ( I guess store would be more for testing and rpc more user facing ).

**Comment by bobbinth** [comment]
> `The endpoint could take two parameters:` but you only list one, could you tell me what the second parameter should / could be ?

Ah - that's a typo. Fixed!

> Why would you want to add a streaming capability to this endpoint?

If we don't limit the number of requested notes, we probably want to stream the notes rather than send one big response (same is probably true if we allow to request data for a very large number of notes).

> This should be implemented on the RPC correct? We have 2 places where it could be implemented for now. RPC and Store ( I guess store would be more for testing and rpc more user facing ).

We need this in both, RPC and store. The RPC endpoint will just forward the request to the store (similar to how we do it for many other endpoints in the RPC).

**Comment by Dominik1999** [comment]
closed by #298
