### ISSUE TITLE
[Feature]: Support for public accounts in the genesis file

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/miden-node#305]
### To whom is this feature for?

End user

### Why is is this feature needed?

It might be useful to create public (on-chain) accounts in genesis. At the moment we don't support public accounts in genesis file. We should discuss, if we need it.

### How is this feature used?

TBD

**Comment by bobbinth** [comment]
I guess there are a couple of options here:

1. The endpoint takes the `block_num` as input and streams all blocks starting at that number until the current block.
2. The connection stays open and the user streams blocks as they are created.
3. (we could also combine the two).

I'm not sure about the complexities (and implications) of the second option - so, don't have a good sense which option we should go with.

Also, regardless of the option, we probably should think about some kind of DoS prevention mechanism as this endpoint can result in returning lots of data. This would probably be related to #52.

**Comment by bobbinth** [comment]
Closed by #365.
