### ISSUE TITLE
[Task]: Address `note_type` enum codegen issues

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#314]
### Node's components affected by this task

- [X] RPC
- [ ] Block producer
- [ ] Store
- [X] Protobuf messages
- [ ] Testing

### What should be done?

On https://github.com/0xPolygonMiden/miden-node/pull/311 we added `note_type` to `NoteSyncRecord`. Ideally this would be an enum in the protobuf messages, but when using something like this:

```
enum NoteType {
  PUBLIC = 0;
  OFF_CHAIN = 1;
  ENCRYPTED = 2;
}
```

The codegen creates conflicting definitions of some types due to deriving some attributes twice. See [this](https://github.com/0xPolygonMiden/miden-node/pull/311#discussion_r1559919146) for more information.

### How should it be done?

Fix the codegen when using enums

### When is this task done?

When on a clean build the types are generated correctly and the protobuf definition files contain the enums.

### Additional context

The linked PR contains mor econtext.

**Comment by bobbinth** [comment]
As a part of #338, we invested this but decided to keep `note_type` as an int.
