### ISSUE TITLE
[Task]: Refactor note-related messages to include a `NoteMetadata` 

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#315]
### Node's components affected by this task

- [X] RPC
- [ ] Block producer
- [X] Store
- [X] Protobuf messages
- [ ] Testing

### What should be done?

Currently note-related messages in protobuf contain the same fields. These should be refactored out into its own `NoteMetadata` object

### How should it be done?

https://github.com/0xPolygonMiden/miden-node/blob/25529ac9bc629e4ac1f0d2c8bc9739b0d1bc2866/proto/proto/note.proto

Change messages to include a new `NoteMetadata` field that looks something like this:

````protobuf
message NoteMetadata {
    account.AccountId sender  = 1;
    uint32 note_type = 2;
    fixed32 tag = 3;
    fixed64 aux = 4; // unsure if we want/need this for a first iteration
}
````

and replaces the pertinent fields.

### When is this task done?

When note messages contain NoteMetadata as a specific field.

**Comment by bobbinth** [comment]
Closed by #338.
