### ISSUE TITLE
[Feature]: Add public notes to the faucet 

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-node#329]
### To whom is this feature for?

End user

### Why is is this feature needed?

Alice loves the new faucet and that she can get a private note with some tokens. Now, she wants also to check out the second flow and receive a public note via the blockchain. 

### How is this feature used?

Alice wants to be able to click either a button "Public notes" or a button "Private notes". 

If she clicks "Public notes" the faucet should execute a transaction using `--note-type public`. If she clicks "Private notes" the type should be `--note-type private`.

### Anything else?

We could add a short explanation how to consume the note then. But we can also add this later

**Comment by bobbinth** [comment]
Closed by #339.
