### ISSUE TITLE
[Feature]: Transform `Faucet` from lib to bin

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#333]
### To whom is this feature for?

App developer

### Why is is this feature needed?

The miden-faucet behaves as as standalone component. It  does not make much sense to couple it with the miden-node considering that it's and optional component.

### How is this feature used?

It will be easier to install and run the miden-faucet binary as a standalone component de-coupled from the miden-node.

### Anything else?

Additional  comment here: https://github.com/0xPolygonMiden/miden-node/pull/323#discussion_r1574221696

**Comment by bobbinth** [comment]
Closed by #332.
