### ISSUE TITLE
[Task]: Store Note's.`aux` field in the database

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#342]
### Node's components affected by this task

- [ ] RPC
- [X] Block producer
- [X] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

We are currently hardcoding `aux` fields of the note metadata internally. We should change the code to pass the value accordingly and storing it in the database.

### How should it be done?

Add a column in the notes SQL table schema for the `aux` field, and store/retrieve it accordingly.

### When is this task done?

When the SQL table includes the `aux` field and it is stored and retrieved accordingly.

**Comment by bobbinth** [comment]
Closed by #384.
