### ISSUE TITLE
[Task]: Modify gRPC Tonic Server to Allow HTTP/1.1 Requests

### ISSUE THREAD

**Issue by dagarcia7** [0xPolygonMiden/miden-node#346]
### Node's components affected by this task

- [X] RPC
- [ ] Block producer
- [ ] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

Implement functionality within the gRPC Tonic server to accept and process HTTP/1.1 requests from gRPC-Web clients. This will enable direct handling of requests without the need for the client to use an external proxy like Envoy.

* Integrate [tonic-web](https://crates.io/crates/tonic-web) with the server setup to enable this functionality. This integration should allow the Tonic server to translate HTTP/1.1 requests into the HTTP/2 format expected by gRPC without needing an external proxy. Here is an example of using `tonic-web` with the current RPC server configuration:

* Ensure that the server can handle both traditional gRPC (HTTP/2) and gRPC-Web (HTTP/1.1) requests.

### How should it be done?

* Integrate the [tonic-web](https://crates.io/crates/tonic-web) crate into the existing Tonic server configuration. This crate facilitates the server's ability to understand and respond to HTTP/1.1 requests as per the gRPC-Web specification. Here is an example of how to modify the existing gRPC server configuration per [tonic-web's documentation](https://docs.rs/tonic-web/0.11.0/tonic_web/).

```Rust
// RPC INITIALIZER
// ================================================================================================

pub async fn serve(config: RpcConfig) -> Result<(), ApiError> {
    info!(target: COMPONENT, %config, "Initializing server");

    let api = api::RpcApi::from_config(&config)
        .await
        .map_err(ApiError::ApiInitialisationFailed)?;
    let rpc = api_server::ApiServer::new(api);

    info!(target: COMPONENT, "Server initialized");

    let addr = config
        .endpoint
        .to_socket_addrs()
        .map_err(ApiError::EndpointToSocketFailed)?
        .next()
        .ok_or_else(|| ApiError::AddressResolutionFailed(config.endpoint.to_string()))?;

    Server::builder()
        .accept_http1(true)
        .add_service(tonic_web::enable(rpc))
        .serve(addr)
        .await
        .map_err(ApiError::ApiServeFailed)?;

    Ok(())
}
```

### When is this task done?

* The task is complete when the server can natively handle gRPC-Web requests sent over HTTP/1.1 alongside traditional gRPC requests over HTTP/2.

* The server passes all integration tests that confirm the server operates correctly with both protocols under various conditions.

### Additional context

The motivation for this enchancement is driven by the need to get `miden-client` executing within a browser context. To do this, we are currently using the [tonic-web-wasm-client](https://crates.io/crates/tonic-web-wasm-client) crate in order to take the Protobuff Message and Service definitions of `miden-node`, and create a client that compiles within the context of WASM and creates gRPC-web compatible requests. Creating a client using the regular [tonic](https://crates.io/crates/tonic) crate doesn't compile in a WASM context because it has downstream dependencies on libraries like `tokio` that rely on OS-level features to perform its operations. However, with the gRPC server configured as it is, it won't accept these gRPC-web requests as they operate over HTTP/1.1. To my knowledge, the only way to get around this on the client side is to go through a proxy like Envoy that can accept gRPC-web requests and transform them to gRPC requests compatible over HTTP/2.0, or modify the server to allow such requests in the first place.

**Comment by bobbinth** [comment]
Closed by #352.
