### ISSUE TITLE
[Task]: Update README to have a more comprehensive installation guide

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#355]
### Node's components affected by this task

- [ ] RPC
- [ ] Block producer
- [ ] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

Update the installation steps in the README.md.

### How should it be done?

Review and clarify the README.
Remove assumptions on file paths and OSs.

### When is this task done?

When the text is concise, correct, and easy to follow by a user

### Additional context

https://github.com/0xPolygonMiden/miden-node/pull/353#discussion_r1597512754

**Comment by Dominik1999** [comment]
@phklive

**Comment by bobbinth** [comment]
Closed by #436.
