### ISSUE TITLE
[Feature]: Standardise Makefile and CI across Miden repositories

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#363]
### To whom is this feature for?

Rollup operator

### Why is is this feature needed?

For now we are using different configurations for the Makefile and CI across the Miden repositories.

We want to standardise this:
- use Make instead of Cargo make
- use Make commands in the CI
- use the same configuration for commands in all repositories

### How is this feature used?

This will improve management of repositories

**Comment by Dominik1999** [comment]
Closed by https://github.com/0xPolygonMiden/miden-node/pull/367
