### ISSUE TITLE
[Feature]: configure whether genesis accounts are public or not

### ISSUE THREAD

**Issue by mFragaBA** [0xPolygonMiden/miden-node#364]
### To whom is this feature for?

App developer

### Why is is this feature needed?

Now that we have both offchain and onchain accounts, it would be nice that genesis accounts could be public accounts.

### How is this feature used?

Either tests or setups that create public accounts can do so within the genesis instead of manually create one or write a script that uses the cli/client.

One use case for example would be in the miden client's integration tests where we can pre-define some accounts to use on tests and making them public allows us to use them in different client instances from different tests. Also sharing an accound between tests might help test different flows for onchain accounts

**Comment by bobbinth** [comment]
Would this be a duplicate of #305?

**Comment by mFragaBA** [comment]
Oh, it is indeed! My bad. I'll close this issue. If no one's working on it and it's ok to do so I can add a config in the genesis file to create accounts on chain @bobbinth . Thanks for the heads up btw

**Comment by bobbinth** [comment]
> If no one's working on it and it's ok to do so I can add a config in the genesis file

Yes - that would be awesome! I will assign that issue to you.
