### ISSUE TITLE
[Task]: Account API for Block Explorer

### ISSUE THREAD

**Issue by 0xs34n** [0xPolygonMiden/miden-node#375]
### Node's components affected by this task

- [ ] RPC
- [ ] Block producer
- [ ] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

- Accounts data for block explorer
- Eg., `GetAccountbyId`
- If private, only ID + state hash, if public, more info below:
- Details regarding state changes overtime
- Latest change at block height 

### How should it be done?

Add an endpoint to retrieve Accounts data

### When is this task done?

When there is a publicly available endpoint to retrieve Accounts data

### Additional context

Please refer #299

**Comment by bobbinth** [comment]
Details about the latest account state can be retrieved via the `GetAccountDetails`. For historical data, similar to my comment in https://github.com/0xPolygonMiden/miden-node/issues/374#issuecomment-2146746574, my understanding was that the block explorer would get all required data from the `GetBlockByNumber` endpoint. Or is it missing something?

**Comment by 0xs34n** [comment]
`GetBlockByNumber` will work for historical. Thanks!

**Comment by bobbinth** [comment]
Great! Should we close this issue?
