### ISSUE TITLE
Enabled processing of transactions involving notes with delegated inclusion proofs

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#381]
As a part of working on https://github.com/0xPolygonMiden/miden-base/issues/353 we've enabled notes whose existence in the chain is not verified by the transaction kernel. We also need to make sure these notes are processed correctly by the node.

To set the context:

- For "regular" notes, the transaction kernel is responsible for proving that the note has been recorded in the chain at some point in the past. For these notes we know only their `nullifier`.
- For "future" notes, transaction kernel does not prove existence - this is delegated to batch/block kernels. Since we don't have these for now, what we need to do is just make sure that transaction data is consistent. For future notes, we know both the `nullifier` and the `note_id`.

At the high level, we need to do the following:
1. When a new transaction is received, if it consumes any "future" notes, in addition to the regular checks (i.e., making sure that the nullifier is not in the nullifier DB), we need to check:
  a. Is the future note already in the note DB. If it is, everything is good and the batch kernel will handle inclusion path verification in the future.
  b. If not, then we need to check if the note is an output note of any transaction which is currently "in-flight" (i.e., exists in the `StateView`).
  c. If neither of the above pass, the transaction should be rejected.
2. When transactions are selected for batching, we should also make sure that the selected transactions have all dependencies satisfied. That is, any "future" notes for this transactions are either already in the chain, or are output notes of "in-flight" transaction batches.
  a. The above also includes the batch being currently built. That is, we can select 2 transactions to go into the batch if one of them depends on the other.
  b. One other thing to keep in mind: if a "future" note is both created and consumed within a batch, it should not be recorded in the batch's note tree. That is, it should look like as if this note never existed.
3. When we build a block, we also need to make sure that all dependencies are satisfied. That is, all "future" notes going into the block are either already in the chain or are outputs of batches going into the block.
 a. This implies that by the time we've built the block, all future notes are "erased". By extension, this means that we shouldn't need to change the `Block` structure or anything in the store - this issue is purely for the block producer.

**Comment by polydez** [comment]
Resolved by these PRs: https://github.com/0xPolygonMiden/miden-node/pull/390 and https://github.com/0xPolygonMiden/miden-node/pull/396.
