### ISSUE TITLE
[Feature]: Add `miden-node init` and `miden-faucet init` commands

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#385]
### To whom is this feature for?

Rollup operator

### Why is is this feature needed?

To enable the easy configuration and portability of the miden node and faucet, for now we need to download or copy paste the config files from github after installing the crate from crates.io

### How is this feature used?

These commands would create default configuration files for the miden node and faucet `node.toml` `genesis.toml` `faucet.toml`

**Comment by bobbinth** [comment]
Closed by #392.
