### ISSUE TITLE
[Task]: Add WASM Support for miden-node-proto Crate

### ISSUE THREAD

**Issue by dagarcia7** [0xPolygonMiden/miden-node#388]
### Node's components affected by this task

- [X] RPC
- [ ] Block producer
- [ ] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

Currently, adding the `miden-node-proto` crate as a dependency for any crate that attempts to support WASM builds fails due to having `tonic` as a dependency. This has had consequences in both the `miden-client` repo and the `miden-wasm` crate that is currently under development and not yet in a miden repository. 

**How this affects the `miden-client` crate:**
* Imports like these https://github.com/0xPolygonMiden/miden-client/blob/68aed5e91705ab7dc980c3b05ba7921e5bc37efc/src/errors.rs#L6, don't work when building the `miden-client` for WASM targets so we had to add a feature to conditionally compile this import for non-wasm builds.
* We also had to copy and paste code https://github.com/0xPolygonMiden/miden-client/blob/68aed5e91705ab7dc980c3b05ba7921e5bc37efc/src/errors.rs#L22 directly from the `miden-node-proto` repo to get it to compile for wasm builds. 

**How this affects the `miden-wasm` crate:**
* Because the `ApiClient` and `ApiServer` are generated via `tonic-build` and thus create auto-generated code that relies on `tonic`, I am also unable to import this code or the `miden-node-proto` crate in general from the `miden-wasm` crate. 
* This code is important to be accessible for this crate because instead of duplicating this code in the `miden-wasm` crate and creating my own wasm-compatible rpc client, there should be a way to support both the regular tonic rpc client that the `miden-client` CLI uses, and a wasm compatible rpc client that can be consumed by the `miden-wasm` crate. 

### How should it be done?

These are just preliminary thoughts, but a potential approach so solve this problem could be:
* Add a feature to the `miden-node-proto` crate that will allow us to conditionally add (or exclude) the `tonic` crate and any other WASM-incompatible crates. 
* Use this feature in combination with https://crates.io/crates/tonic-web-wasm-client to create an auto-generated `ApiClient` (called `WebApiClient`, `WasmApiClient`, or something similar) so that this client can be imported into the `miden-wasm` crate without any issues. 

### When is this task done?

This task is done when the following two are possible: 
* `miden-node-proto` can be listed as a dependency in the `miden-client` for both WASM and non-WASM targets
* The `ApiClient` (no need for the `ApiServer`) in `miden-node/crates/proto/src/generated/rpc.rs` is generated in such a way that allows for safe consumption in the `miden-wasm`crate. 

### Additional context

Related discussions in recent `miden-client` PR
    * https://github.com/0xPolygonMiden/miden-client/pull/378#discussion_r1630952918
    * https://github.com/0xPolygonMiden/miden-client/pull/378#discussion_r1639948388

**Comment by bobbinth** [comment]
A few preliminary thoughts from my end:

I'm not sure `miden-client` should depend on `miden-node-proto` - or at least not in the way it is done now. A couple of reasons for this:

- The only thing we really need for the client are the protobufs fro the RPC endpoints. All internal protobufs (e.g., for the store and block producer) are not really needed.
- I am not sure we should make any opinionated decisions in the node repo about what the clients might need beyond the protobuf files. For example, why support just tonic and tonic web but not Go etc.

So, I think it might be good to generate all the relevant Rust files in the client repo. There, if the `tonic` feature is enabled, we'd generate tonic-specific files. If some other feature is enabled (e.g., `tonic-web`), we'd generate files for that specific framework.

If we go with the above approach, I think the main question is how to get the protobuf files to the client. One option is to piggy-back on crates.io for distribution. Here's how it could work:

- First, we move `.proto` files from `/crates/proto/proto` to the root of this repo (i.e., into just `/proto`).
- Then, we create a new crate (e.g., something like `miden-rpc-proto`). This crate would be very simple:
  - We'd embed all `.proto` files into it as strings (e.g., using [include_str](https://doc.rust-lang.org/std/macro.include_str.html) macro).
  - It would expose a single function - e.g., something like `write_proto()` - which would write the embedded files into a directory.
- This crate would be used a build dependency in the client to fetch protobuf files during the build process and then auto-generate code from them as needed.

I think it should work - but does fill a bit hacky - so, I'm open to other suggestions as well.

**Comment by bobbinth** [comment]
Closed by #391.
