### ISSUE TITLE
[Feature]: Add specialized endpoint for getting note inclusion paths

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/miden-node#395]
### To whom is this feature for?

App developer

### Why is is this feature needed?

We need to get inclusion path for each unauthenticated note in the store in order to check the inclusion proof in batch/block kernels. Now we use `GetNotesById` endpoint for this, but it returns a lot of unnecessary information for this particular task. Thus, we need a specialized endpoint for this, something like `GetNoteInclusionProofs`, which will consume multiple note IDs and return IDs and merkle paths of each note from the requested set. Notes not found in the store should be omitted from the response, no errors should be thrown in this case.

We also need to modify the `GetBlockInputs` input to also return inclusion paths for all found unauthenticated notes.

### How is this feature used?

For providing note inclusion proofs to transaction kernel.

**Comment by bobbinth** [comment]
A couple of small comments:

- We need the inclusion paths not for the transaction kernel but for batch/block kernels.
- I would call the endpoint something like `GetNoteIncludionProofs`.
- We also need to modify the `GetBlockInputs` input to also return inclusion paths for all found unauthenticated notes.

**Comment by bobbinth** [comment]
Closed by #421.
