### ISSUE TITLE
Sort batches within a block by dependency order

### ISSUE THREAD

**Issue by polydez** [0xPolygonMiden/miden-node#397]
@bobbinth:

At the block level, output notes must come before corresponding unauthenticated input notes. That is, if `batch1` has an unauthenticated input note `A`, this note must be an output note of `batch0` (e.g., having it be an output note of `batch2` should not be allowed).

**Comment by bobbinth** [comment]
I think this is somewhat related to the "Loosen block selection strategy" item from #519.

**Comment by Mirko-von-Leipzig** [comment]
Closed by #572
