### ISSUE TITLE
Add `NoteExecutionHint` to the store

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#439]
### Node's components affected by this task

- [ ] RPC
- [ ] Block producer
- [X] Store
- [ ] Protobuf messages
- [ ] Testing

### What should be done?

Recently, `NoteExecutionHint` was added to the `NoteMetadata` struct. We need to store and retrieve this accordingly.

### How should it be done?

Add the field into the SQL databases and queries, and store/retrieve it accordingly for transaction outputs.

### When is this task done?

When we can return the correct note metadata on note queries.

**Comment by bobbinth** [comment]
Closed by #441.
