### ISSUE TITLE
Drop wallet account from default genesis data

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [0xPolygonMiden/miden-node#446]
> Not related to this PR, but I'm thinking we should have only a single faucet account in the genesis block as I'm not sure there is much value in pre-creating a wallet account as well (the reason we had this originally is because very early on we didn't have a way to create new accounts and so having a wallet account in the genesis made testing possible). Let's create an issue for this.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-node/pull/436#discussion_r1721020380_

**Comment by polydez** [comment]
Resolved by https://github.com/0xPolygonMiden/miden-node/pull/510
