### ISSUE TITLE
Improve version strings

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [0xPolygonMiden/miden-node#493]
Improve the output of our `miden-xxx --version` output to account for non-release builds, such as we might deploy on devnet instances.

Use `git describe --tags --dirty` which will give us the format

```
<version-tag>-<commit-count>-<commit SHA>-dirty
```

where everything but `<version-tag>` is only present if applicable.

This will also help us debug operator node's as we can now know if they're on a non-release build.

**Comment by bobbinth** [comment]
Closed by #495.
