### ISSUE TITLE
[block-producer]: follow-up tasks

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [0xPolygonMiden/miden-node#519]
Follow-up tasks from #515. Some of these require work in `miden-base`.

- [x] ~Create and use `ProposedBatch` in `miden-base` ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807946778))~ Tracked in #583 
- [x] Use a more correct `BatchId` ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807947418))
- [x] ~Create and use `ProposedBlock` in `miden-base` ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807948590))~ Tracked in #583 
- [x] Loosen block selection strategy ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807964589))
- [x] #523
- [x] Improve block/batch simulation times ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807966960) and [source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1807967683))
- [x] Amend `GetTransactionInputs` to found instead of missing notes ([source](https://github.com/0xPolygonMiden/miden-node/pull/515#discussion_r1809596677))
- [x] Instrument mempool
- [x] Wrap `AuthenticatedTransaction::inner` in an `Arc` for cheaper copies.
- [x] Move graph tests into a separate `tests.rs` file.
- [x] Move batch limits from `TransactionBatch` into the mempool's batch selection strategy
- [x] Move block limits from the block builder into the mempool's block selection strategy
- [x] Remove transactions from the error variant of batch builder error and in general revisit all errors there.
- [x] #564 
- [x] #565
- [x] #566

**Comment by bobbinth** [comment]
Nice! I added this issue to the current milestone, though probably not everything will end up there (e.g., `ProposedBatch` and `ProposedBlock` is definitely for the next milestone).
