### ISSUE TITLE
Add `AccountCode` to `GetAccountProof` endpoint

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#520]
For FPI, we need to load an `AccountCode`'s commitment |-> `AccountCode` mapping into the advice provider. 
However, the `GetAccountProof` endpoint does not return it. 
We could make it so that the API request includes an  optional`AccountCode` commitment, and the endpoint returns an `Option<AccountCode>`, where the value is `Some(AccountCode)` if the current code version is different than the provided one and `None` otherwise.

**Comment by bobbinth** [comment]
Closed by #521.
