### ISSUE TITLE
[Bug]: Get stuck when executing the make-genesis command

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonMiden/miden-node#536]
### Version

v0.5.1

### What happened?

After cloning code, I execute the `make-genesis` command on my Mac, as follows: 
```
/miden-node/target/debug/miden-node make-genesis --inputs-path config/genesis.toml --output-path miden/genesis.dat --force
2024-11-01T10:14:27.781221Z  INFO miden_node::commands::genesis: bin/node/src/commands/genesis/mod.rs:84: Genesis input file: miden/genesis.dat has successfully been loaded.
2024-11-01T10:14:39.104061Z  INFO miden_node::commands::genesis: bin/node/src/commands/genesis/mod.rs:132: Creating basic wallet account...
2024-11-01T10:35:11.233177Z  INFO miden_node::commands::genesis: bin/node/src/commands/genesis/mod.rs:150: Creating fungible faucet account...
```
Then it get stuck here, even waiting for a long time.  By debugging the program, I found the blocking is caused  by  [mpsc channel
](https://github.com/0xPolygonMiden/miden-base/blob/a5a2058124c4820788037aefef407fbef09b7a00/objects/src/accounts/seed.rs#L53).  
But how to fix it?

### What should have happened?

It should create fungible faucet account smoothly.

### How can this be reproduced?

1. clone main branch;
2. run: ./target/debug/miden-node make-genesis --inputs-path config/genesis.toml --output-path miden/genesis.dat --force

**Comment by Mirko-von-Leipzig** [comment]
Hey @Federico2014, thanks for the report and write up. 

Account creation can take a while because it involves solving a crypto puzzle. Quoting from the install section of our readme:

> [!TIP]
> Miden account generation uses a proof-of-work puzzle to prevent DoS attacks. These puzzles can be quite expensive, especially for test purposes. You can lower the difficulty of the puzzle by appending `--features testing` to the `cargo install ..` invocation. For example:
> ```sh
> cargo install miden-node --locked --features testing
> ```

So I guess two questions:

1. Did you compile with the `--features testing` set?
2. How long did you wait for?

**Comment by Federico2014** [comment]
@Mirko-von-Leipzig Thank you for your reminder.  I compiled it by running the `make build` command. The `testing` feature seems to be on, but I am not sure.   I waited at least an hour.  I will try again.

**Comment by Federico2014** [comment]
@Mirko-von-Leipzig After adding the `testing` features,  it worked. Thank you for your support.

**Comment by Mirko-von-Leipzig** [comment]
No problem :) We're aware its a pitfall; there is some ongoing work that should hopefully remove the need for this entirely in the future.
