### ISSUE TITLE
transaction consistency mode

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#56]
ref: https://github.com/0xPolygonMiden/miden-node/pull/51#pullrequestreview-1705237215

**Comment by bobbinth** [comment]
A couple questions to figure out here:

- Do we want to use WAL or rollback mode for SQLite.
- Do we want to put all read queries into transactions.

**Comment by hackaugusto** [comment]
implemented by https://github.com/0xPolygonMiden/miden-node/pull/143 and https://github.com/0xPolygonMiden/miden-node/pull/70 .

- WAL was used to allow for concurrent reads while the DB is being updated.
- All SQL statements are executed inside a transaction, include SELECTs, the transaction is open/closed implicitly. A explicit transaction was not added because it was not sufficient, since the node updated the DB and in-memory stores. Locking/Synchornization was added to handle these cases.
