### ISSUE TITLE
[block-producer]: increase block frequency

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [0xPolygonMiden/miden-node#564]
> let's reduce block times to 5 seconds.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-node/pull/562#discussion_r1870439574_

**Comment by varun-doshi** [comment]
Can i take this?

**Comment by Mirko-von-Leipzig** [comment]
> Can i take this?

Apologies just implemented this :)
