### ISSUE TITLE
Use `thiserror` consistently across the crate

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#62]
From https://github.com/0xPolygonMiden/miden-node/pull/55#discussion_r1385685335.

I advocate that we use [thiserror](https://docs.rs/thiserror/latest/thiserror/) for errors across the repo.

Pros:
- Implements `std::error::Error` for you
- Implements `Display` for you (with the attribute `#[error("display string for error variant")]`
- Doesn't appear in the public API, so we can stop using it at any point without breaking changes
- Convenience attributes, such as `#[from]` which implements a `From` for the variant that it's defined on (which plays nicely with the `?` operator)
- Widely used, and well maintained (by dtolnay)

Cons:
- Doesn't work with `no_std`, only due to the fact that `std::error::Error` lives in `std` instead of `core`, but this is eventually [going to change](https://github.com/rust-lang/project-error-handling/issues/3)

Alternatives:
- We could go with `anyhow` or `eyre` instead if we want to write "one-off errors" (no enums defined) everywhere and lose the ability to match on specific error variants. We can also use both: `thiserror` for all library code, and `anyhow` in the binary or anywhere we're absolutely certain the error is only meant to be printed out to the user

**Comment by bobbinth** [comment]
For the node, I don't think we are aiming for `no_stdd` support - so, I think using `thiserror` is fine.

**Comment by bitwalker** [comment]
We use both `anyhow` and `thiserror` in the compiler, leaning more on custom error types via `thiserror` than `anyhow`, but I have nothing but good things to say about both projects.

**Comment by hackaugusto** [comment]
Just to clarify, the goal here is to use `thiserror` in addition to `anyhow`, correct?

**Comment by bobbinth** [comment]
Not sure of pros and cons - but seems like we should mostly lean on `thiserror` and use `anyhow` only in binaries?

**Comment by bitwalker** [comment]
I would only use `anyhow` in functions which join together different error types from the same crate. If you find yourself writing error types with multiple "#[error(transparent)]" variants, that's a sign `anyhow::Error` is a better fit there. Within a crate, it can still be useful to keep strongly-typed errors so that you can handle those errors. Once something is an `anyhow::Error`, it's a lot more awkward to handle errors directly, and more likely that they just get yeeted up the stack.
