### ISSUE TITLE
`NullifierBlockInputRecord` should also return nullifier value

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#63]
[Here](https://github.com/0xPolygonMiden/miden-node/blob/81547375a1361f01bdbf63acb4994856af4b47de/proto/src/generated/responses.rs#L96-L101). This will allow the block builder to validate that indeed the nullifiers in the block being built haven't been produced yet.

Context: [comment](https://github.com/0xPolygonMiden/miden-node/pull/55#discussion_r1385656953)

**Comment by bobbinth** [comment]
Superseded by #140.
