### ISSUE TITLE
`DefaultTransactionQueue`: Ensure at most 2^12 created notes per batch

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#65]
Related: #64

**Comment by bobbinth** [comment]
I think this may be as simple as making sure that if batch builder gets a list of more than $n$ transactions (i.e. [here](https://github.com/0xPolygonMiden/miden-node/blob/main/block-producer/src/batch_builder/mod.rs#L130), it would return an error. $n$ should probably be defined in `miden-base` (i.e., [here](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/lib.rs#L57)). We could call it `MAX_TRANSACTIONS_PER_BATCH` and it would be computed based on `NOTE_TREE_DEPTH`.

**Comment by bobbinth** [comment]
> We could call it `MAX_TRANSACTIONS_PER_BATCH` and it would be computed based on `NOTE_TREE_DEPTH`.

Actually, we need one more constant to support this: `MAX_BATCHES_PER_BLOCK`. Then, `MAX_TRANSACTIONS_PER_BATCH` is defined as `2.pow(NOTE_TREE_DEPTH - MAX_BATCHES_PER_BLOCK.ilog2())`.
