### ISSUE TITLE
Handle CLI serve commands

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#75]
Currently the host and port from the CLI are being ignored, e.g.:

https://github.com/0xPolygonMiden/miden-node/blob/8366d47c20c71fe5fe1c0d0ce8b1b7638a410308/store/src/main.rs#L25-L27

These options should be merged with the configuration:

https://github.com/0xPolygonMiden/miden-node/blob/8366d47c20c71fe5fe1c0d0ce8b1b7638a410308/utils/src/config.rs#L45-L50

Making sure to give higher priority to the CLI arguments.

docs: https://docs.rs/figment/latest/figment/#for-cli-application-authors

**Comment by bobbinth** [comment]
Superseded by #124.
