### ISSUE TITLE
`block_builder` tests: fix and use new infrastructure

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#79]
#77 introduced a new infrastructure useful especially for the `block_builder` tests. It is currently incomplete, and needs to be fixed before every `block_builder` test can be updated to use it. Specifically

- `MockStoreSuccessBuilder` and `build_expected_block()` need to compute the correct notes root
- `MockStoreSuccessBuilder`: `new()` needs to be replaced with a few different constructors (including `from_batches()`) which allow it to know the initial account IDs and state.

Once this is done, use this new test code everywhere, and remove the obsolete `DummyProvenTxGenerator`.

**Comment by hackaugusto** [comment]
@plafer could you add more context on what needs to be done? What should be achieved by this issue?

**Comment by plafer** [comment]
The ultimate goal is to get rid of [`DummyProvenTxGenerator`](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/proven_tx.rs#L131). 

The objects that I started creating to replace/enhance its functionality are:

- [`MockProvenTxBuilder`](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/proven_tx.rs#L35): has methods to create a mock `ProvenTransaction`
- [`TransactionBatchConstructor`](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/batch.rs#L3): provides convenience functions to create batches
- [`MockBlockBuilder`](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/block.rs#L96): a builder to create a mock block

These are already used in some tests (except for `TransactionBatchConstructor`) - all other tests should be written using those. You'll probably need to adapt them too. Feel free to redesign them too if you prefer - again, as long as we get rid of `DummyProvenTxGenerator`.

**Comment by hackaugusto** [comment]
Thanks for the update.

> The ultimate goal is to get rid of [DummyProvenTxGenerator](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/proven_tx.rs#L131).

And why do we want to get rid of it? What features is it lacking that are introduced by the other mocks?

**Comment by plafer** [comment]
It was a hack at the time before we had [`StarkProof::new_dummy()`](https://github.com/facebook/winterfell/pull/232). The only way to create a `StarkProof` object was by running the winterfell prover on a bogus problem (i.e. all [this](https://github.com/0xPolygonMiden/miden-node/blob/bcfcf2809d74b77c5d9f8366cf34d0b46fead2cc/block-producer/src/test_utils/proven_tx.rs#L191-L325)). Running this makes tests slower, and just isn't clean.

With the other mocks, I also took this change as an opportunity to create objects that make tests more readable and reduce the amount of copy/paste. It's still a WIP though (and hence this issue).
