### ISSUE TITLE
feature flags to disable/enable services

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#92]
we have implemented a node binary, that runs all 3 services (`rpc`, `block_producer`, and `store`) in the same process. this simplifies a lot of things including stdin/stdout/stderr, process management, shutdown, testing.

now that we have a single binary, we can add flags or subcommands to control which services are executed, e.g. `miden-node services run`, `miden-node store run`, `miden-store rpc run`. 

This approach simplifies a few things:

- deployment, specially with static linking since a single binary can be copied to multiple machines, and only the process management config need to change to choose which service is executed.
- compilation, since we don't have to compile 3 binaries, but a single one, we should get a small speed up
- testing, since we no longer have to add infrastructure to build and test multiple binaries
- user onboarding, we can do releases of a single binary per platform, and an operator can just download that to do testing

**Comment by plafer** [comment]
Relating to #100, this means that we only ever need just one config file. If someone wants to run e.g. only the `store`, then they only need to have the `[store]` header in their config.

**Comment by bobbinth** [comment]
Closed by #323.

**Comment by Kosi23** [comment]
Hi @Mirko-von-Leipzig — I’d like to take a crack at this one if it’s still open.
My read of the issue plus the discussion thread on #1846: the asymmetry between SubmitProvenBatch (which validates the reference block via a store lookup) and SubmitProvenTransaction (which delegates to the block-producer) means clients get different error semantics for the same bad input, and every batch submission round-trips to the store even though reference blocks cluster heavily around the tip.
Plan I’d propose:
	1.	Add a small LRU header cache in the RPC component (sized to recent blocks — capacity configurable, sensible default), wrapping the existing SubmitProvenBatch reference-block lookup so misses fall through to the store and populate the cache.
	2.	Move the same reference-block check onto SubmitProvenTransaction’s RPC path, returning the same error variant SubmitProvenBatch already returns so clients see consistent semantics.
	3.	Tests covering hit/miss/eviction on the cache and an integration test asserting both endpoints reject a non-existent reference block uniformly.
Two questions before I start:
	•	Any preference between lru and a hand-rolled bounded cache here? I noticed the codebase already pulls in parking_lot so I’d default to a parking_lot::Mutex<LruCache<_, _>> unless the lookup path is fully async, in which case tokio::sync::Mutex.
	•	Should the cache live on the RPC component itself or be exposed through whatever store-client wrapper the RPC uses? The latter feels cleaner if other endpoints might benefit later, but I don’t want to expand scope.
Happy to be assigned if this looks like the right direction.
