### ISSUE TITLE
Add full docker-compose

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#93]
The full production system will need some auxiliary services. Namely metrics, tracing, log collection, and in the future maybe a DB. These systems are big and requires a bit of configuration effort, and we should have them available in a testing environment for a few reasons 1. ensure it works in production 2. having these capabilities can be super useful to debug, optimize, and have general insight of the system.

These services are inherently stateful, and once in a while we need to test multiple versions (say, for an upgrade, or change in schema in a dev version that should run on a new instance). The best way to isolate and manage these details in via container technology.

Docker compose is one possibility. But it may be useful to do some researching, MacOS seems to finally got support to container technologies and there may be some better alternatives out-there. For linux I would recommend going with podman, which is compatible with docker/docker-compose.

**Comment by hackaugusto** [comment]
it seems podman actually supports macos nowadays: https://www.redhat.com/sysadmin/run-containers-mac-podman , there are also lima, minikube, rancher, and possibly other options that I missed.

**Comment by okcan** [comment]
Hi agusto, I have a question, why is there a search for macos?

**Comment by hackaugusto** [comment]
@okcan do you mean search of a container stack for macos? for development, most of the team is using macos. running the system inside container for E2E testing makes it easier to test against new environments (i.e. new OS images), to do process cleanup (i.e. just shutdown the cgroup), to test in parallel (by isolating the network/ports in cgroups), and so forth.

**Comment by okcan** [comment]
Sorry, I misunderstood for a moment haha :D

**Comment by phklive** [comment]
Considering the potential refactor of the node from 4 binaries to 1 binary we will close this issue and look into adding a Docker compose in the future if needed. #92
