### ISSUE TITLE
Flag to reduce cost of PoW for testing

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#94]
miden-base has a feature flag to lower PoW cost while testing:

https://github.com/0xPolygonMiden/miden-base/blob/main/miden-lib/Cargo.toml#L17-L18

We should enable that flag here too for testing.

**Comment by bobbinth** [comment]
@plafer - this is already implemented, right?

**Comment by plafer** [comment]
Ah, yes!
