### ISSUE TITLE
Decide on how to define the genesis block for testing

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#96]
Things to decide:

- how many
    - on/off chain accounts, what initial balances
    - fungible / non-fungible tokens 
- how to modify and distributed the above

related: https://github.com/0xPolygonMiden/miden-node/issues/94

**Comment by hackaugusto** [comment]
This is related to the mock tool from miden-base https://github.com/0xPolygonMiden/miden-base/tree/main/mock . But this issue is how to do similar changes for the servers, which involves the store and not just a serialized file to disk.

**Comment by bobbinth** [comment]
I wondering if we should make genesis block a part of the startup config (or maybe another file which is required to be provided to start the node).

For example, if we describe genesis block as a JSON file, we could pretty easily modify its contents and add/remove accounts in the future.

At the startup time, the node would read this file and if the chain hasn't been started yet (i.e., the store is empty) would use it as a starting point. If the chain is already running, it would just verify that the provided genesis block matches the first block in the store.

**Comment by hackaugusto** [comment]
+1 for a config file. That would also allow people to generate their own genesis for testing purposes.

**Comment by plafer** [comment]
> I wondering if we should make genesis block a part of the startup config (or maybe another file which is required to be provided to start the node).

Yes! This is how Cosmos SDK-based chains [do it](https://hub.cosmos.network/main/resources/genesis.html#what-is-a-genesis-file).
